// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCqpJw1WPgCwQsF-21n0TzOdb_nfMqeM4',
    appId: '1:991451158756:android:9edc01ee22d6dd6e5ab4f1',
    messagingSenderId: '991451158756',
    projectId: 'flutter-myinsta-c4e3d',
    storageBucket: 'flutter-myinsta-c4e3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSgMPt1VaWwdiM8orBrvJ_3jpCu-qc2Qg',
    appId: '1:991451158756:ios:c989769cd982aa455ab4f1',
    messagingSenderId: '991451158756',
    projectId: 'flutter-myinsta-c4e3d',
    storageBucket: 'flutter-myinsta-c4e3d.appspot.com',
    iosClientId: '991451158756-m9lg1qaqg055i5qv7tpf35gjac3ej2vq.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaclone',
  );
}
